name: CI
on: [pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js LTS
        uses: dcodeIO/setup-node-nvm@v2.0.0

      - name: Yarn install
        run: |
          yarn --frozen-lockfile --non-interactive

      - name: Test
        run: |
          yarn validate
          yarn test:ci
        env:
          CI: true

      - name: Build
        run: |
          yarn build

      - name: Deploy preview
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          args: deploy --message "${{ github.base_ref }}"
          secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
