name: CI
on: [pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Use Node.js 12.x
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'

      - name: yarn install, and test
        run: |
          yarn install --frozen-lockfile
          yarn test:ci
        env:
          CI: true

      - name: build
        run: |
          yarn build
