name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: dcodeIO/setup-node-nvm@v2.0.0

      - name: Upgrade Yarn
        run: npm install yarn@latest -g

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore Yarn/node_modules cache
        uses: actions/cache@master
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./node_modules
          key: ${{ runner.os }}-yarn-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-node-modules-

      - name: Restore Gatsby cache
        uses: actions/cache@master
        with:
          path: |
            ./.cache
            ./public
          key: gatsby-cache

      - name: Yarn install
        run: |
          yarn --frozen-lockfile --non-interactive

      - name: Build
        run: |
          yarn build

      - name: Deploy
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          DEPLOYMENT_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          npm install netlify-cli@^2.0.0 -g -s
          netlify deploy --prod --message "${DEPLOYMENT_MESSAGE}"
